Alamofire 5 and bumped Monri iOS version
jasminsuljic/monri-ios pull request #22
Opened 2024-01-24 11:05 UTC by harunk-monri

2024-01-24 16:04 UTC, jasmind-monri approved these changes
LGTM

2024-01-31 08:17 UTC, jasminsuljic requested changes

2024-01-31 08:17 UTC, jasminsuljic commented on Monri.podspec
> +  s.version          = '1.4.2'
Increase version to 1.5.0

In readme add notification about major dependency version upgrade, something like:
```markdown
## Version 1.5.0

In version 1.5.0 we have upgraded Alamofire dependency from `~4.0` to `~> 5.2.1`. If you encounter any issues with dependency upgrade let us know through GitHub issues or by sending an email to helpdesk@monri.com`

```

2024-02-01 08:15 UTC, jasminsuljic approved these changes

2024-02-01 08:16 UTC, merged